name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List files in repository
        run: ls -l
      
      - name: Build Docker image
        run: docker build -t juliocesarferreira/atvsomativa5:v1 -f Dockerfile .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: juliocesarferreira
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to Docker Hub
        run: docker push juliocesarferreira/atvsomativa5:v1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      
      - name: Check image vulnerabilities with Trivy
        run: |
          trivy image juliocesarferreira/atvsomativa5:v1 > trivy_report.txt
      
      - name: Show Trivy report
        run: cat trivy_report.txt

  configure-pages:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
          token: ${{ secrets.TOKEN }} # Usando o token padr찾o do GitHub
          enablement: true # Tentar habilitar Pages para o reposit처rio se ainda n찾o estiver habilitado

  deploy:
    runs-on: ubuntu-latest
    needs: configure-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.TOKEN }}
          folder: .  # Indicando a pasta raiz do reposit처rio
          branch: main
