name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Etapa para construir a imagem Docker
      - name: Build Docker image
        run: docker build -t juliocesarferreira/atvsomativa4:v1 .
      
      # Instalação do Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # Verifica as vulnerabilidades na imagem usando Trivy
      - name: Check image vulnerabilities with Trivy
        run: |
          trivy juliocesarferreira/atvsomativa4:v1

      # Etapa para fazer o login no Docker Hub (ou outro registro de contêineres)
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: juliocesarferreira 
          password: .Julio123

      # Etapa para construir e enviar a imagem Docker para o registro de contêineres
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            juliocesarferreira/atvsomativa4:v1
            juliocesarferreira/atvsomativa4:latest
