name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List files in repository
        run: ls -l
      
      - name: Build Docker image
        run: docker build -t juliocesarferreira/atvsomativa4:v1 -f Dockerfile .
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      
      - name: Check image vulnerabilities with Trivy
        run: |
          trivy image juliocesarferreira/atvsomativa4:v1 > trivy_report.txt
      
      - name: Show Trivy report
        run: cat trivy_report.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: juliocesarferreira 
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            juliocesarferreira/atvsomativa4:v1
            juliocesarferreira/atvsomativa4:latest
